apiVersion: v1
kind: Service
metadata:
  name: regapp-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: regapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
