apiVersion: v1
kind: Service
metadata:
  name: regapp-service
  namespace: default
  labels:
    app: regapp
spec:
  type: NodePort
  selector:
    app: regapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32387   # or remove and let K8s assign
