apiVersion: apps/v1
kind: Deployment
metadata:
  name: regapp-deployment
  namespace: default
  labels:
    app: regapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: regapp
  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp
        image: devopscentraltest/registration-app:latest
        ports:
        - containerPort: 8080

        # ---- HEALTH CHECKS FOR ARGOCD ----
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10

        # ---- OPTIONAL (GOOD PRACTICE) ----
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
