apiVersion: v1
kind: Service
metadata:
  name: regapp-service
  namespace: default
  labels:
    app: regapp
spec:
  selector:
    app: regapp
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
