apiVersion: v1
kind: Service
metadata:
  name: teaching-service
  labels:
    app: teach
spec:
  selector:
    app: teach
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31711
