apiVersion: apps/v1
kind: Deployment
metadata:
  name: teach-deployment
  namespace: default
  labels:
    app: teach
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teach
  template:
    metadata:
      labels:
        app: teach
    spec:
      containers:
      - name: teach
        image: devopscentraltest/registration-app:41
        ports:
        - containerPort: 8080

        # ---- HEALTH CHECKS (FIXED PATH) ----
        readinessProbe:
          httpGet:
            path: /registration-app/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /registration-app/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3

        # ---- RESOURCE LIMITS ----
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
