apiVersion: apps/v1
kind: Deployment
metadata:
  name: teach-deployment
  namespace: default
  labels:
    app: teach
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teach
  template:
    metadata:
      labels:
        app: teach
    spec:
      containers:
      - name: teach
        image: devopscentraltest/new_teching_image:39
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

        # -------- ENV VARS FOR DB --------
        env:
        - name: DB_HOST
          value: "52.204.45.34"
        - name: DB_NAME
          value: "admin"
        - name: DB_USER
          value: "adminuser"
        - name: DB_PASS
          value: "StrongPassword@123"

      # REMOVE PROBES FOR NOW
        # -------- READINESS PROBE --------
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 20
        #   periodSeconds: 5
        #   failureThreshold: 5
    # -------- LIVENESS PROBE --------
        # Temporarily disabled while we debug CrashLoopBackOff
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
        #   failureThreshold: 3

        # -------- RESOURCE LIMITS --------
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
