apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teaching-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/Devops-central-test/registration-manifests.git'
    targetRevision: main
    path: teaching        # <-- FOLDER containing teach_deploy.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
